### ISSUE TITLE
キャラクター選択画面の背景

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#10]
今はゲーム画面の背景をキャラクター選択画面で出してるけど、実際にキャラクター選択画面に表示する背景(3Dの部分)はどうする？
半透明でキャラクター選択画面作っているようだから後ろでOSKの文字を象ったモデルを回転させるとか、何かエフェクトをかけておくとか。
この部分に関して仕様が決まってないので意見がほしい。

**Comment by coil398** [comment]
それぞれのモデルにあった背景画像を用意するのがいいかなと思う。
それか、それっぽい背景画像用意して、全部それとか

**Comment by 921starfish** [comment]
キャラクターごとに背景を変えられるようなら、選択していないキャラの画像をぼんやり出しておいてもいいかもしれません。

逆に全キャラ統一なら、応用数学研究部の名前が入っているモデルがいいと思います。（ここ以外で応数研の名前自然に出せるところといえば(仕様未定の)gameover画面だけだと思うので）

**Comment by kyasbal** [comment]
ぼんやり出すってのは、Oculusだとうまく見えないかもなぁ。
