### ISSUE TITLE
モーションキャプチャについて

### ISSUE THREAD

**Issue by 921starfish** [kyasbal/MagicalFPS#11]
放課後等教室を借りてモーションキャプチャをする計画があります。
教室をバラバラに借りることを避けるために、教室を借りるのは部長主導で行うそうです。
MMD担当の方および参加する方は、都合の悪い時間・希望する時間があればこのissueにコメントしてほしいです。

**Comment by ahy4** [comment]
MMD佐藤です
今週は
火,水,木: 5限まである
金,日: すいません参加できません
なお終電は0:31発です

**Comment by kyasbal** [comment]
来週の教室を借りる場合、できれば金曜日までに分かるといろいろ楽です。
ちなみに僕も居たほうがいいなら金曜日以外の任意の曜日で可能です。

**Comment by kyasbal** [comment]
んー、MinTearのほうはいつでも問題ないの？
多分MinTear主体で行うなら、何か返答ないと予定立てにくいと思うけど。

**Comment by MinTear** [comment]
火曜日以外は大丈夫
来週はテストがあるので月～水は出来ればなしで
後はみんなの都合と合わせます

**Comment by kyasbal** [comment]
他のMMD班の人たちは？

**Comment by 921starfish** [comment]
大窪と僕ですね。
僕も皆に合わせますが、来週だけは木曜以降がいいです。
大窪は今githubのアカウントを作ってもらっているところなので、ここがまだ見れないため、今日聞いておきます。

**Comment by 921starfish** [comment]
大窪は
今週は木曜日。
来週は月曜日、水曜日、木曜日が空いているそうです。

**Comment by ahy4** [comment]
そうだそういえば来週以降について特に言ってなかったですがおそらくいつでも大丈夫です。
レポートが終わってないので毎日みたいには行けなさそうですが

**Comment by kyasbal** [comment]
では、来週の木曜ではどうでしょう？
僕も一応参加しますし。

**Comment by kyasbal** [comment]
木曜の放課後に教室を借りるようセバスチャンに言っておきます？

**Comment by ahy4** [comment]
了解です！お願いします

**Comment by 921starfish** [comment]
では、とりあえず6/12日の放課後ということでこのissueは閉じておきますね。
