### ISSUE TITLE
明日の会合

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#12]
連絡が遅くなりましたが、木曜日に会合を一度するということだったので教室をとってあります。
(18:00~22:30まで)
Kinectの実験をしつつモーショントラッキングでモーションを作ることに関する議論を行います。
教室の場所は部室に貼ってある紙を見ないとわからないので、放課後に部室に集合ということにしましょう。
参加できない方はいますか？

**Comment by coil398** [comment]
バイトじゃった

**Comment by kyasbal** [comment]
モーション作成の人たちだけだからいいんじゃね

**Comment by 921starfish** [comment]
今日の活動は終了しました。
来週は木曜日の予定です:star:

**Comment by sensu-star** [comment]
了解です(∩´∀｀)∩

**Comment by kyasbal** [comment]
モーションはんの人たちは進んでるー？

**Comment by 921starfish** [comment]
とりあえず私はMMDの導入までです……

**Comment by sensu-star** [comment]
僕もMMD導入して自分で少し遊んでみたりしましたが本格的なことはまだやってません…
