### ISSUE TITLE
MagicalFPSの今後について

### ISSUE THREAD

**Issue by MinTear** [kyasbal/MagicalFPS#13]
開発を主にしてくれていたLimeStreemさんが忙しくなるので、
制作に関わるのが難しくなりました。
制作期限もあるので、今回はUnityを使おうと思います。

Unityはユニティ・テクノロジーズが開発したゲームエンジンで
C#やJavascriptに対応しています

ゲーム開発以外にも使われたりするほど多機能で、
企業で使われるくらいの品質が高いものなのでこれがベストだと思いました

話は変わりますが、今制作するメンバーが少なく一人一人の負担が大きいです
長期休暇手伝えそうな人、興味がある人はぜひ協力してください

今制作は止まっていましたが、少しずつ初めていきます
今まで手伝ってくれていた人もよろしくお願いします

**Comment by kyasbal** [comment]
LimeStreemさん今までありがとう！
僕らの心の中に君の意志は生き続けるよ！

**Comment by MinTear** [comment]
そうして、彼の姿は消えてしまいました・・・

**Comment by kyasbal** [comment]
ツッコミ待ちだったのに！

**Comment by MinTear** [comment]
わざとじゃないよ（笑）

**Comment by kyasbal** [comment]
今後メインで開発していく人へ(MinTearとstarfish)
http://atnd.org/events/53125
ここでUnity学んで来い。
