### ISSUE TITLE
ステージの作成

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#2]
ステージのモデルの作成。
まだどのレベルまでなら重くならないかわからないので、軽めの物で構わない。
COLLADAファイル形式で提出。

**Comment by kyasbal** [comment]
ステージの問題は以後ここに。

**Comment by 921starfish** [comment]
明日の話し合いって聞いてても大丈夫ですか？

**Comment by kyasbal** [comment]
おう。
2014/05/30 22:57 "921starfish" notifications@github.com:

**Comment by kyasbal** [comment]
結局テストで表示するステージとかはどのくらい出来たのでしょうか？

**Comment by MinTear** [comment]
全然進めてない・・・
MMDは少しづつ進めて
ステージ作りを優先していくことにします

**Comment by kyasbal** [comment]
ステージの進捗はどうかい？

**Comment by MinTear** [comment]
今週中に一ついけるようにする、ゲームの使様上
・魔法を撃つスペースは十分に確保する
・隠れることができる

２つを意識するとステージが同じようなものしか思いつかない
アイデアが枯渇しているので他の人の意見もください

**Comment by kyasbal** [comment]
アイデア募集するなら今のところのステージの画像みたいな
2014/06/05 9:21 "MinTear" notifications@github.com:

**Comment by MinTear** [comment]
ごめん家にしかないけど大したものでもないので
部室で作るからその時にみんなのアイデアがもらえればと思います

**Comment by kyasbal** [comment]
進捗するたびに、ステージのスクリーンショットとかあるといいね

**Comment by MinTear** [comment]
ステージをテストプレイ用に作りました

![stage2 blend](https://cloud.githubusercontent.com/assets/7471721/3210784/26dfb8ea-eee6-11e3-87e2-0ca42329082d.png)
![stage1 blend](https://cloud.githubusercontent.com/assets/7471721/3210785/26e1c27a-eee6-11e3-97de-54aeb301820a.png)

上のようにとてもシンプルなものになりました
改善できるようBlenderの勉強を進めます
テクスチャや法線マップはできる限り早く作成します

**Comment by kyasbal** [comment]
了解です。
一つだけ注意点が。
1枚のポリゴンだけの壁はやめてください。薄くても厚みを持った立方体を利用して壁を構成してほしいのです。

**Comment by MinTear** [comment]
片方修正しました画像です
もう一方も同じように修正しておきます

![stage3 blend](https://cloud.githubusercontent.com/assets/7471721/3211424/f445fb3e-ef16-11e3-979e-5cb36a8431a6.png)

**Comment by kyasbal** [comment]
ステージで来たらどっかにうｐしてアドレス張っておいて。
