### ISSUE TITLE
モデルごとに必要なモーションの列挙

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#3]
実装することが決まったモデルごとに、必要なモーションを列挙する。
例えば、
「モナー用歩き」、「モナー用攻撃モーション1」など。
モーション作成者が悩まないように、一般的ではないモーションを用意する際はその説明を用意すること。

**Comment by 921starfish** [comment]
とりあえずCharacterListに追加していきます。

**Comment by kyasbal** [comment]
いいね。こんな感じでissueを使いこなしていこう。
このタスクが終わったらissueはclosedにしておいてね。

**Comment by coil398** [comment]
ここでいいのかな？
正直いきなりやるゲームで、バリアを使いこなすのは難しいと思うので
避けるの重視でバリア廃止してもいいかも。

**Comment by kyasbal** [comment]
モーションデータをとり始める段階での仕様としては纏まってきたのでこの問題はこれでClosedとします。
