### ISSUE TITLE
開発環境の構築及びその確認

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#4]
現在のソースコードの動作チェックをせよ。
注意点
このプロジェクトはMMFを利用している。単体では動作しない。以下を参考に。

1、MMFをこのレポジトリの作業コピーがあるフォルダーと同階層にフォルダー「mmflex」を作りクローンする。

2、feature/oculusSensorブランチをチェックアウト

出来たものは報告、出来なかった者も報告。
環境構築は重要なので、分からないから放置する事などないようにしてください。それだけ作業が遅れます。
また、できるかぎりこのissuesにコメントして質問しよう。同じような問題を抱えている人が多いはずだ。

環境構築済みリスト
- [x] ライム野郎
- [x] 921starfish
- [x] coil398
- [x] MyYD
- [x] MinTear
- [ ] emelenthia

**Comment by 921starfish** [comment]
できました。

**Comment by coil398** [comment]
mmflex\MikuMikuFlex\OculusForMikuMikuFlex
のOculusForMikuMikuFlex以下のファイルってどこにありますか？

**Comment by kyasbal** [comment]
feature/ oculusSensorをチェックアウトしてるかな？
多分だから出てないんだとおもう

**Comment by coil398** [comment]
チェックアウトの仕方を教えていただきたいです。

**Comment by kyasbal** [comment]
SourceTreeの該当するリモートの上で右クリックしてチェックアウトを選んでください。
2014/05/29 13:23 "coil" notifications@github.com:

**Comment by coil398** [comment]
![image](https://cloud.githubusercontent.com/assets/7694377/3115436/71ec65f8-e708-11e3-852a-f22bd1629175.png)
こんなエラーがでました。

**Comment by kyasbal** [comment]
ソリューション右クリックして、nuggetのパッケージの復元の有効化してください
2014/05/29 17:08 "coil" notifications@github.com:

**Comment by 921starfish** [comment]
ちょっと話がずれますが、

![caputure](https://cloud.githubusercontent.com/assets/7694387/3116443/f4c47f22-e719-11e3-8b21-71e8ef3a7e5b.GIF)

mmflexを追加した後のこの「コミットされていない変更があります」はコミットしたほうがいいのでしょうか？

**Comment by coil398** [comment]
![image](https://cloud.githubusercontent.com/assets/7694377/3116676/471c2488-e71e-11e3-94a8-0ad6a52539ff.png)
復元を有効化してからビルドしたところこうなりました。

**Comment by kyasbal** [comment]
えーと、まず最初に今後質問をする際には、以下を明確にしてくれると助かります。
・エラーの原因の予測(調べた結果類似するエラーへの対処法など書かれたページなどもあればURLを張って)
・自分が試行したエラーへの対処

その上で、返答しておきます。
まず、ソリューション内の各プロジェクトについて参照設定を開き、三角形のエラー表示がないか確認してください。
多分、あると思います。そしたらその””名前を覚えたうえで””その参照を削除してください。
そしたら該当するプロジェクトで右クリックしnugetパッケージの管理より、先ほど覚えた名前で検索してインストールを押してください。
これをすべての参照設定、プロジェクトに対して繰り返してください。

**Comment by MinTear** [comment]
全然関係ないんだけど、ステージは地面と建物ぐらいでいいのかな
空とか壁はDirectXで設定するの?

2014年5月30日 1:02 ライム野郎 notifications@github.com:

**Comment by kyasbal** [comment]
空はやるよ
壁ってのは何を指してるの？

**Comment by MinTear** [comment]
プレイヤー同士が離れすぎないための行き止まりみたいなやつです

2014-05-30 18:54 GMT+09:00 ライム野郎 notifications@github.com:

**Comment by kyasbal** [comment]
それはこちらでやります
2014/05/30 19:45 "MinTear" notifications@github.com:

**Comment by MinTear** [comment]
分かった
いつぐらいまでに出来ればいいのかな

**Comment by kyasbal** [comment]
明日早めに来れる？
色々話そう
2014/05/30 20:36 "MinTear" notifications@github.com:

**Comment by MinTear** [comment]
問題ないです
時間はそちらにお任せする

**Comment by kyasbal** [comment]
じゃあ9時で。
8時50から教室つかえるから。
2014/05/30 22:43 "MinTear" notifications@github.com:

**Comment by MinTear** [comment]
了解です

**Comment by kyasbal** [comment]
あと、ステージに関する問題については別にissue作って置きます。
今度から話題が違う場合は別のissue作成してね

**Comment by MinTear** [comment]
分かった

**Comment by kyasbal** [comment]
環境がその後整った人、動かなくなってしまった人は報告しましょう。

**Comment by emelenthia** [comment]
MMF参照設定内のNiWrapperはx64とx86のどちらをインストールすればいいのでしょうか?

**Comment by kyasbal** [comment]
最新版のプルで解決できない？
2014/06/01 18:13 "emelenthia" notifications@github.com:

**Comment by emelenthia** [comment]
MMFは恐らく最新版(6/1 14:30版)ですが、"log4net","NiWrapper.Net","NiWrapper.NITE.Net"の3つに
黄色い三角が表示されてます。

**Comment by kyasbal** [comment]
んー,NiWrapper.netはx86で。
log4netはプロジェクトのディレクトリにdllがあります

**Comment by emelenthia** [comment]
それらについては恐らく解決しました。

![snapcrab_magicalfps - microsoft visual studio_2014-6-1_20-28-35_no-00](https://cloud.githubusercontent.com/assets/7638021/3141488/0572fe8a-e980-11e3-8070-0d1ae3f89b31.png)

しかし、このようなエラーが出てしまい、また、多くの参照が上手くいっていないように見えます。
両者ともバージョンは18:30頃版です。どうすればいいのでしょうか?

**Comment by kyasbal** [comment]
参照しているSharpDXのバージョンが違うんじゃないかと思う。
SharpDXを一度nugetで外して、
https://github.com/LimeStreem/MagicalFPS/wiki/VIsualStudio
を参照にして2.4.2のSharpDXを入れて。

**Comment by kyasbal** [comment]
その後ビルドが通らなくなった人がいたら報告してください。

**Comment by 921starfish** [comment]
通らなくなりました。
![error](https://cloud.githubusercontent.com/assets/7694387/3168766/b84bd850-eb89-11e3-8f29-e467f2bf0d91.gif)
![error](https://cloud.githubusercontent.com/assets/7694387/3168767/c0dbb7ba-eb89-11e3-8a47-abce98ffe59c.gif)
IJoystickKeyConfigとIKeyboardKeyConfig関係みたいです。

**Comment by kyasbal** [comment]
ソースコードが一部除外されてると思う。
解決できるかな？
2014/06/04 10:47 "921starfish" notifications@github.com:
