### ISSUE TITLE
プレイヤーキャラクター選択画面の作成

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#5]
プレイヤーキャラクターの選択画面を作成する。
以下の要件を満たすように作成せよ。
- 選択しているキャラクターの画像を表示できること。
- 選択しているキャラクターの名前、スキル名などの説明を表示できること。
- キーボードもしくはジョイスティック入力による左右の入力で次もしくは前のキャラクターが選択できるようにする。

また、以下の点に注意すること。
- キャラクターが増えても対応できるようにキャラクターの数などはリテラルとせずに定数として定義せよ。
- 本来、キャラクターの情報などはテキストファイルなどから読み込むのが合理的でメンテナンス性に優れるが、今回は配列から読み込めればよい。

今回作成したコードに対して、僕のほうでリファクタリングを行うが、変数名関数名などについてはある程度配慮したうえで作成せよ。

**Comment by MrYD** [comment]
はい
batch.DWRenderTarget.FillRectangle(col,batch.FillRectangle);
三角形の書き方教えてもらっていいですか

**Comment by kyasbal** [comment]
いえ帰ったら書く。
ちょっと難しいよ
2014/05/30 23:40 "MrYD" notifications@github.com:

**Comment by MrYD** [comment]
あ、はい

**Comment by kyasbal** [comment]
MMFの2D機能はDirect2D及びDirectWriteのラップによって成り立っています。
簡易的な形状は以前教えた方法を利用することができますが、複雑な形状に関してはDirect2Dの機能を直接扱います。
複雑な形状はジオメトリを利用します。特定の経路によって囲われる形状である場合、PathGeometryを利用します。
ジオメトリの初期化は以下のように行います。
これをonLoad内に用意してください。_geometryはPathGeometry型のフィールドです。

```
        _geometry = new PathGeometry(Context.RenderContext.D2DFactory);
        GeometrySink geometrySink = _geometry.Open();
        geometrySink.SetFillMode(FillMode.Winding);
        geometrySink.BeginFigure(new Point(800, 0), FigureBegin.Filled);
        geometrySink.AddLine(new Point(1200, 600));
        geometrySink.AddLine(new Point(0, 400));
        geometrySink.EndFigure(FigureEnd.Closed);
        geometrySink.Close();
```

これにより3頂点(800,0),(1200,1600),(0,400)によって囲われる三角形を意味するジオメトリを作成できました。
手順は以下のように行った。
- PathGeometryを構成する経路を設定するクラスGeometrySinkを_geometry.Openで取得した。
- geometrySink.BeginFigureで最初の頂点と、塗り方を宣言した。
- さらにAddLineでポイントを追加してその点への線分を引いていく。
- EndFigureでClosedを指定して作った形状の始点と終点を結ぶ。
- 形状が完成したらCloseをしてgeometryの作成は終了。

これを利用して以下のようにDrawBatch内で呼ぶことで、ジオメトリを描画する。

```
        batch.DWRenderTarget.FillGeometry(_geometry,col);
```

また、いろいろ応用がきく。
今回はLineによって三角形を構成したが頂点間はBezier曲線を用いることや弧を用いることができる。
詳しくは、以下を参考にせよ。なお例はC++の例なので適宜C#に読み替えて記述すること。
http://msdn.microsoft.com/en-us/library/windows/desktop/ee264309(v=vs.85).aspx
しかし、Geometryの生成処理は比較的重い処理であるから、OnLoadのときに行う。

**Comment by MrYD** [comment]
出来ました。
ありがとうございます。

**Comment by kyasbal** [comment]
それはよかった。
他にいろいろある手法についても試してみるといい。
他のところでも役立つかもしれぬ。

**Comment by kyasbal** [comment]
以下のMrYDによるコミットについて
7f0ada4dee69a41b7d8d6c53bdf9e24e792ebbac

コードへのコメントで書いた通り、リソースを絶対パスで指定しているので他の人が動かないので修正してください。
他の人が動かないような状態にテスト的になる場合、コミットだけでプッシュはせず、動くようになってからプッシュしてください。

**Comment by MrYD** [comment]
了解

**Comment by MrYD** [comment]
修正しました

**Comment by kyasbal** [comment]
了解。ちなみに修正したときはコミット時に
#issue番号(これならば #5)と書き込めばこっちのissueにコミットのコメントが来ます)

**Comment by MrYD** [comment]
「キャラクターイメージパスを相対パスに変更」のあとに間違った操作をしプッシュした可能性がありプロジェクトが起動しません

**Comment by kyasbal** [comment]
エラー内容を教えてください

**Comment by MrYD** [comment]
消してはいけないファイルを消したのだと思います。
「５０MB以上もの・・・」までリセットしてからもう一度相対パスに変更します。

**Comment by kyasbal** [comment]
はい。
今後のためにもエラーなどはスクリーンショットとかはっといてくれると、同じ問題になったひとの解決のためにもなります。
2014/06/01 14:14 "MrYD" notifications@github.com:

**Comment by kyasbal** [comment]
![エラー内容](http://i.gyazo.com/d1c6ec30e98b8ae98ee48475623f920b.png)

おそらく言っているのはこの内容かな？
多分俺のミスだから改善するプッシュを出す・・・

**Comment by kyasbal** [comment]
上記問題はコミット d2b6d57a16afb373dd95b7196600436f0c4d4c13 を以て解決。
