### ISSUE TITLE
モーション作成者の拡充

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#7]
正直、モーションを作成する人が足りない気がする。
MinTearはステージ作成で十分に仕事が大量にあるだろうし、モーション作成に将来的に回ってもらうにしてもモーションの量が膨大だ。
モーション作成者は現状で2名以上用意したいところだと思ってる。
とはいってもMMDを普段触れている人などいないし、新たに勉強してもらうことになると思うのだが、ちょうどいい人はいないだろうか？

みんなの意見を求む。githubのissueへのコメントの抵抗感をなくすためにも。

**Comment by 921starfish** [comment]
とりあえず明日の活動で全体に呼びかけてみるのはどうでしょうか。

**Comment by kyasbal** [comment]
そうですね。とりあえず明日は呼びかけようとは思います。
しかし、全体に呼び掛けると担当したいといってくる方は少ないと思います。
実際にできそうな人、こういうのが好きそうな人がいるなら名指しで協力しないか聞いてみるのが効果的だと思っています。
もし、その候補がいればぜひあげてほしいです。

**Comment by 921starfish** [comment]
モーション作成者に大窪が参加してくれるそうです。

**Comment by kyasbal** [comment]
彼のgithubのユーザー名を聞いてください
2014/06/02 17:41 "921starfish" notifications@github.com:

**Comment by 921starfish** [comment]
彼に聞いたところGithubのアカウントを作った時に休んだのでまだアカウントを作ってないそうです。
今度会えるときに作って貰います。

**Comment by kyasbal** [comment]
集まったようなのでclosedとします。
