### ISSUE TITLE
キャラクターモデルについて

### ISSUE THREAD

**Issue by 921starfish** [kyasbal/MagicalFPS#8]
当初の予定通り、登場キャラクターを  
初音ミク、霧雨魔理沙、金剛、八頭身モナー  
に決定します。
モナー以外のキャラクターのMMDモデルについては、近日中にこのissueで数モデルを提案します。

また（結局使わなかった）wikiのCharacterWishListを廃止しますので、もし希望があるようでしたら、このissueに書いてください。 

その際は、登場する作品の二次創作についてのガイドラインと、そのモデルのモデル利用規約などに書いてある二次利用の可否を確認してください。

↓template↓
### 名前

配布先URL<br>
攻撃/防御/HP/素早さ/加速度<br>
(特技)

| 動き | 技名 | 威力 | 効果 |
| :-: | :-: | --: | :-- |
| ? | 技名 | 威力 | 効果 |
| ? | 技名 | 威力 | 効果 |
| ? | 技名 | 威力 | 効果 |

「キャラの簡単な説明」

**Comment by 921starfish** [comment]
### Tda式Appendミク

http://3d.nicovideo.jp/works/td1586  
攻撃/防御/HP/素早さ/重さ  
(特技)

| 動き | 技名 | 威力 | 効果 |
| :-: | :-: | --: | :-- |
| A | みっくみくにしてあげる:notes: | 75 | 広範囲・強技 |
| B | ネギカッター | 70 | 広範囲・弱技 |
| C | ネギバリア | 無し | 全方位バリア |

初音ミクのモデルの一つです。欠点として重いことがあげられますが、モデルを少しいじれば使えるかも？ということで載せます。
技に関しては今日出た案を参考にしてみましたが、仮ということで。

**Comment by kyasbal** [comment]
とりあえず、まだ仮の案かもしれないんだけど幾つか改善点。
- エフェクトのイメージがほしい。
- 「広範囲・強技・弱技」は説明になっていない。このような記述をするのならこれらの用語を定義してください。

それともう一つ。
Tda式Appendミクの外観の特徴とA,B,Cの技は合わない感じを受けます。
はちゅねミクの採用もひとつ考慮に入れてはどうでしょう？

**Comment by 921starfish** [comment]
### ぷっぴぴミク

配布先URL  
http://ux.getuploader.com/prominence/  
http://ux.getuploader.com/prominence/download/24/%E3%81%B7%E3%81%A3%E3%81%B4%E3%81%B4%E3%83%9F%E3%82%AF.zip
ですね。検討してみます。  
エフェクトのイメージはダメージ計算にも必要となると思いますので、準備出来しだい追加します。  
「広範囲・強技・弱技」等、説明になっていない用語に関しては後ほどwikiで定義します。

**Comment by 921starfish** [comment]
さっき途中送信してしまいました。コメントを更新しておきました。

**Comment by 921starfish** [comment]
### 金剛（制作:つみだんご氏）

http://www.nicovideo.jp/watch/sm22025972
http://bowlroll.net/up/dl23158
（パス：21649701）

ほぼ唯一の金剛のモデル（派生モデルはある）。武装なしver.があるので、何とか使えるかも。

**Comment by kyasbal** [comment]
MMWTで表示できるなら使えるから、表示テストもしといて
2014/06/01 16:12 "921starfish" notifications@github.com:

**Comment by 921starfish** [comment]
#### 表示テスト

はちゅね、金剛、にがもん式の表示が成功しました。（はちゅね、金剛はpmxに変更後）

### にがもん式魔理沙

http://www.nicovideo.jp/watch/sm18003162
http://ux.getuploader.com/super_sierra/download/13/MarisaV12.zip
（パス：sm18003162）

にがもん氏制作の魔理沙モデル。MMD杯優勝動画に出ていたことや、クッキー☆界隈で使われたこともあり、幅広い層に知名度は高いと思われる。

先述の金剛とともにボーン数が300を超えている。モデル改造が必要かもしれない。

**Comment by MinTear** [comment]
モーション作成の仕方一通り理解して歩きモーション今作ってるけど、
死ぬほどめんどくさい
やはりあと2,3人いると楽
いないならしょうがないけど

**Comment by kyasbal** [comment]
やっぱりなあ。
つらいな・・・

**Comment by MinTear** [comment]
効率を上げるためモーションツールは積極的に使っていこうと思う

MMDをやってみたい人は講座がニコニコ動画に転がってるので
参考にしてほしい
上に使うモデルもあるのでぜひ

**Comment by kyasbal** [comment]
うん。それでもいいと思う。

**Comment by MinTear** [comment]
よく分からなかったら俺が教えたらいいし

関係ないけど意外と楽しい

**Comment by kyasbal** [comment]
楽しいのはいいね！続けばそれだけ技術も身につく・

**Comment by kyasbal** [comment]
モデルの確定を早めにお願いします。

**Comment by 921starfish** [comment]
そうですね。全体的にモーション作成が難しそうなモデル達ですが、MMDにまわれる人もある程度いそうなので、
- ぷっぴぴミク
- 金剛（つみだんご）
- にがもん式魔理沙
- モナー

でCharacterListに載せようと思います。

**Comment by kyasbal** [comment]
それで確定したならば、モデルの身長を合わせる作業をしなければなりませんね。
