### ISSUE TITLE
魔方陣エフェクト

### ISSUE THREAD

**Issue by kyasbal** [kyasbal/MagicalFPS#9]
とりあえず作ってみたよー
http://i.gyazo.com/62dc8812f88279a7d969ec218a309713.mp4
他にどんな感じにしたらいいのかな？

**Comment by kyasbal** [comment]
ビームのエフェクトも作ってみた。
![ビームエフェクト](https://lh3.googleusercontent.com/-T_pI_Le_ZcI/U4tChRGDVFI/AAAAAAAAANM/E8ChEY821Ic/w1598-h799-no/beam.png)

エフェクト作成、これは案外時間かかるわ・・・

**Comment by kyasbal** [comment]
エフェクトの件で疑問だけども、金剛のエフェクトがほとんど同じって地味すぎない？

**Comment by 921starfish** [comment]
戦艦ってことと、提案された技の名前から大砲の弾みたいなのをイメージしてみたのですが、確かに単調で地味ですね。
艦これの二次創作やアンソロとかってどうしてるんでしょう？

**Comment by kyasbal** [comment]
他の人もどう思ってるか意見ほしいね。傍観じゃなくてさ。

**Comment by coil398** [comment]
う～ん、MMD動画漁って見てるけど
実際に弾を発射してるものが見つからない・・・。

**Comment by kyasbal** [comment]
徹甲弾、榴弾、通常弾みたいに分けるとか？
徹甲弾は壁貫通とかで。

**Comment by coil398** [comment]
個人的にはミサイルみたいなの一発
拡散弾みたいなのをばらまくみたいなイメージがありますね。

**Comment by kyasbal** [comment]
誘導弾かー。不可能じゃないけど面倒かもねえ

**Comment by coil398** [comment]
誘導ではないです。
基本的には、長距離高火力狭い範囲技と近距離低火力広範囲技にしたい。

**Comment by MinTear** [comment]
地雷とかないの？
弾打つだけだと面白味にかけちゃうよね

**Comment by coil398** [comment]
地雷とは違うかもだけど、ステージ上のギミックは欲しいかも・・・。
